---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smkn3b/public_html/si_smkn3boy/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R bower_components $DEPLOYPATH
    - /bin/cp -R build $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R node_module $DEPLOYPATH
    - /bin/cp -R plugins $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R user_guide $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .env.production $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp readme.rst $DEPLOYPATH
